config/routes.rb
Flipware::Application.routes.draw do
  get "people/index"

  resources :people

  root :to => "person#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :person
  
  
  validates_presence_of :address1, :city, :zipcode, :address_type, :country
  # this will to change at some point to be international
  validates_length_of :zipcode, :is => 5
  validate :validate_address_type
  
  before_save :update_address_type
  
  
  def ==(address)
    self_attrs = self.attributes
    other_attrs = address.respond_to?(:attributes) ? address.attributes : {}
    [self_attrs, other_attrs].each { |attrs| attrs.except!("address_type", "id", "created_at", "updated_at", "order_id") }
    self_attrs == other_attrs
  end
  
  def clone
    Address.new(self.attributes.except("id", "updated_at", "created_at", "address_type"))
  end


  protected
  
  # forces the newest address to be the current address, but only if it's a new record
  #  otherwise you're just editing it and
  # if we explicitly set the address type to current, force the others to be past ones
  def update_address_type
      Address.update_all "address_type = 'past'", ["person_id = ?", self.person_id] if (self.new_record?) || (!self.new_record? && self.address_type == "current")
  end
  
    
  def validate_address_type
    return if address_type.blank?
    errors.add(:address_type, :invalid) if !["current", "past"].include?(address_type)
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  
  validates_presence_of :first_name, :last_name
  has_many :parent_child_relationships, :class_name => "PersonRelationship", :foreign_key => :parent_id, :dependent => :destroy 
  has_many :parents, :through => :parent_child_relationships, :source => :child
  
  has_many :child_parent_relationships, :class_name => "PersonRelationship", :foreign_key => :child_id, :dependent => :destroy
  has_many :children, :through => :child_parent_relationships, :source => :parent
  
  has_one :current_address, :class_name => "Address", :conditions => "address_type = 'current'", :dependent => :destroy

  has_many :addresses, :dependent => :destroy
  
  def full_name
    self.first_name + " " + self.last_name
  end
end

app/models/person_relationship.rb
class PersonRelationship < ActiveRecord::Base
  belongs_to :parent, :class_name => "Person"
  belongs_to :child, :class_name => "Person"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end
  
  def show
    @person = Person.find_by_id(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flipware</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_person.html.erb
<div>
	<span><%= person.first_name %></span>
	<span><%= person.last_name %></span>
	<div id="parents"></div>
	<div id="children"></div>
</div>

app/views/people/index.html.erb
<h1>Posts#index</h1>

<div id="people">
	<% @people.each do |person| %>
	<%= link_to "#{person.first_name} #{person.last_name}", person_path(person), :class => "person", :remote => true %>
  <% end %>
</div>
<div id="person">
</div>

app/views/people/show.html.erb
<!-- same as render :partial => "person", :object => @person -->
<%= render @person %>

app/views/people/show.js.erb
$("#person").html("<%= escape_javascript(render @person) %>");
// $("#people a") in application.js
//   .bind("ajax:success", function (data, status, xhr) {
//     $("#person").html(data)
//   });